
server:
    port: 8848
#datasource:
#    driverClassName: com.mysql.jdbc.Driver
#    url: jdbc:mysql://rm-wz90iqp704299r20fno.mysql.rds.aliyuncs.com/quchuang_zhengshi?zeroDateTimeBehavior=CONVERT_TO_NULL&useUnicode=true&characterEncoding=utf-8&autoReconnect=true&serverTimezone=GMT%2B8&rewriteBatchedStatements=true
#    username: boshi
#    password: Boshikeji2020##*
#    type: com.alibaba.druid.pool.DruidDataSource

mybatis:
    type-aliases-package: com.cm.special_enterprise.pojo
    mapper-locations: classpath:mapper/*.xml

elasticsearch:
    rest:
        uris: http://192.168.0.95:29200
        connection-timeout: 60s
#        read-timeout: 1200s
#        password: boshikeji
#        username: elastic
spring:
    application:
        name: eureka-server
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://192.168.0.24:3306/datacenter-biz?zeroDateTimeBehavior=CONVERT_TO_NULL&useUnicode=true&characterEncoding=utf-8&autoReconnect=true&serverTimezone=GMT%2B8&rewriteBatchedStatements=true
        username: root
        password: Boshi@888
eureka:
    client:
        register-with-eureka: false
        fetch-registry: false

