server:
    port: 8080
spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: root
        password: 123456
        url: jdbc:mysql://192.168.0.95:23306/enterprise-platform?serverTimezone=UTC&userUnicode=true&characterEncoding=utf-8
        type: com.alibaba.druid.pool.DruidDataSource

mybatis:
    type-aliases-package: com.cm.special_enterprise.pojo
    mapper-locations: classpath:mapper/*.xml

elasticsearch:
    rest:
        uris: http://121.37.230.190:9200
        connection-timeout: 60s
        read-timeout: 1200s
        password: Boshikeji2021##*
        username: elastic


